# Generated by Django 5.0.2 on 2024-03-14 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='email@gmail.com', max_length=200),
            preserve_default=False,
        ),
    ]
