# Generated by Django 5.0.2 on 2024-03-15 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_userprofile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
